# Generated by Django 6.0 on 2026-03-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_note_picture"),
        ("orders", "0004_part_historicalinvoice_hourly_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="vehicle",
        ),
        migrations.AddField(
            model_name="note",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="orders.order",
            ),
        ),
    ]
