# Generated by Django 6.0 on 2025-12-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=55)),
                ("last_name", models.CharField(max_length=55)),
                ("mobile_number", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("vin_code", models.CharField(max_length=17, unique=True)),
                ("number_registration", models.CharField(max_length=10, unique=True)),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("hy", "Hybrid"),
                            ("el", "Electro"),
                            ("di", "Diesel"),
                            ("pe", "Petrol"),
                        ],
                        max_length=2,
                    ),
                ),
                ("last_service", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="crm.client",
                    ),
                ),
            ],
        ),
    ]
