# Generated by Django 6.0 on 2025-12-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "ordering": ["last_service"],
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
    ]
