# Generated by Django 6.0 on 2026-03-15 13:25

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("retail_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_level", models.IntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "part",
                "verbose_name_plural": "parts",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("50.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="labor_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="mileage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Vehicle mileage at the time of service",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("50.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="labor_hours",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="mileage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Vehicle mileage at the time of service",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="parts_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total cost of parts. Should match sum of Order Items.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="parts_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total cost of parts. Should match sum of Order Items.",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPart",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True, help_text="Stock Keeping Unit", max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("retail_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_level", models.IntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical part",
                "verbose_name_plural": "historical parts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Retail price at the time of order",
                        max_digits=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="orders.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
        migrations.CreateModel(
            name="HistoricalOrderItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Retail price at the time of order",
                        max_digits=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.order",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical order item",
                "verbose_name_plural": "historical order items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
